### ISSUE TITLE
Implement domain model for links between arXiv e-prints and external resources

### ISSUE THREAD

**Issue by erickpeirson** [arXiv/arxiv-external-links#1]
We need a core domain class that defines a external relation assertion, in ``relations/domain.py``.

Relation data are immutable. 

  - Add means create new assertion about relation.
  - Edit means create new assertion that supercedes a previous assertion.
  - Deactivate means create new assertion that a previous relation is incorrect, should be suppressed.

Relation data model includes  

  - Type of relation
  - E-print id and version
  - Type of resource
  - Canonical identifier for resource (doi, uri, etc)
  - Freeform description of relation
  - Datetime added
  - Client + user who created
  - identifier of relation superceded or suppressed

Consider something like ``typing.NamedTuple``.

**Comment by erickpeirson** [comment]
For an example of some domain classes with NamedTuple, check out https://github.com/arXiv/arxiv-canonical/tree/develop/arxiv/canonical/domain

**Comment by bonotake** [comment]
So can we refer to some existing classes like `Identifier` in https://github.com/arXiv/arxiv-canonical/blob/develop/arxiv/canonical/domain/identifier.py, or should we define (duplicate) types/classes solely in this project?

**Comment by erickpeirson** [comment]
Any of the stuff in the arxiv-base repo is fair game: https://github.com/arXiv/arxiv-base/tree/master/arxiv

But otherwise as much as possible should be defined locally.

**Comment by bonotake** [comment]
It seems difficult to predefine which type of resources are there. Is it better to define it as just a string?

**Comment by erickpeirson** [comment]
I'd say starting simple makes sense, and we can always revise. The important thing is to capture a sense of the core concepts, e.g. that there is an e-print, there are links, the links can have types, etc
