### ISSUE TITLE
Use case: API client can read all active links between e-print and external resource

### ISSUE THREAD

**Issue by erickpeirson** [arXiv/arxiv-external-links#4]
> As a developer of an information systems/platform, I want to be able to develop against a RESTful JSON API that supports retrieving an array of all active external relations for an individual e-print and a summary of who added the information, so that I can fill in incomplete data in my system and make informed choices about what to include.

Variation 2:
> ... So that I can develop a user interface that presents external links to users.

This will require an endpoint that supports GET requests, with the e-print id (and optional version) as a URL parameter.

We may want a query param to toggle condensed and detailed views, eg for application that doesn't require provenance.

**Comment by bonotake** [comment]
I'll take this.

**Comment by bonotake** [comment]
My code is almost up. Will make a PR after #15 is merged.

**Comment by bonotake** [comment]
@erickpeirson Now it's time to close this, isn't it?

**Comment by erickpeirson** [comment]
Indeed!
