### ISSUE TITLE
Write JSON Schema for e-print external relations view

### ISSUE THREAD

**Issue by erickpeirson** [arXiv/arxiv-external-links#5]
This should describe (as ``schema/resources/links.json``) the JSON view implemented for #4 .

**Comment by bonotake** [comment]
@erickpeirson Maybe I can do it, but I don't know where this schema should be used.
Should we check JSONs generated in #4, or just publish it to users?

**Comment by bonotake** [comment]
Ah, the implementation of #4 (i.e., #8, `controllers` and `services`) did not generate any JSON, but #11 (#24, i.e., `routes`) does.

**Comment by erickpeirson** [comment]
Fixed in #26
